name: 'Build Drupal 8+ artifact'
description: 'Create an artifact release archive from a Drupal composer repository'

outputs:
  filename:
    description: 'Artifact archive full filename'
    value: release-${{ steps.sha.outputs.sha7 }}.tar.gz
  base:
    description: 'Artifact base name'
    value: release-${{ steps.sha.outputs.sha7 }}
  sha7:
    description: 'Artifact base name'
    value: ${{ steps.sha.outputs.sha7 }}

runs:
  using: 'composite'
  steps:
    - name: "Compute SHA"
      id: sha
      run: echo "sha7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: 'Compress release'
      run: tar cvfz release-${{ steps.sha.outputs.sha7 }}.tar.gz --exclude=web/.csslintrc --exclude=web/.eslintignore --exclude=web/.eslintrc.json --exclude=web/.example.gitignore --exclude=web/.gitignore --exclude=web/.ht.router.php --exclude=web/example.gitignore --exclude=web/INSTALL.txt --exclude=web/README.md --exclude=web/update.php --exclude=web/web.config --exclude=web/modules/README.txt --exclude=web/profiles/README.txt --exclude=web/themes/README.txt --exclude=web/sites/development.services.yml --exclude=web/sites/example.settings.local.php --exclude=web/sites/example.sites.php --exclude=web/sites/example.sites.php --exclude=web/sites/README.txt --exclude=node_modules *
      shell: bash

#    - name: 'Upload artifact'
#      uses: actions/upload-artifact@v3
#      with:
#        name: release-${{ steps.sha.outputs.sha7 }}.tar.gz
#        path: ./release-${{ steps.sha.outputs.sha7 }}.tar.gz
